import type { BarSeedData } from './bar-seed.types.js';

export const barSeedPart05: BarSeedData[] = [
  {
    name: 'GAK Seoul',
    address: '서울 종로구 관철동 지하1층 10-1',
    city: 'Seoul',
    latitude: 37.568727,
    longitude: 126.9873516,
    description: 'A sophisticated cocktail bar offering creative, handcrafted drinks in an intimate setting.',
    photos: [
      'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800',
      'https://images.unsplash.com/photo-1485872299829-c673f5194813?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Negroni', price: 14, currency: 'USD' },
      { name: 'Sidecar', price: 16, currency: 'USD' },
      { name: 'Gin & Tonic', price: 12, currency: 'USD' },
      { name: 'Golden Hour', price: 17, currency: 'USD' },
      { name: 'Anchovy Bruschetta', price: 13, currency: 'USD' },
      { name: 'Onion Rings', price: 10, currency: 'USD' },
    ],
  },
  {
    name: 'Gong-Gan',
    address: '서울 종로구 율곡로3길 66-4 안국동',
    city: 'Seoul',
    latitude: 37.5785311,
    longitude: 126.9823954,
    description: 'An artful cocktail bar where each drink tells a story.',
    photos: [
      'https://images.unsplash.com/photo-1605270012917-bf157c5a9541?w=800',
      'https://images.unsplash.com/photo-1540189065-3c6af6b0ea18?w=800',
      'https://images.unsplash.com/photo-1595951821958-0f5fcdfcb7e1?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Pisco Sour', price: 15, currency: 'USD' },
      { name: 'Rob Roy', price: 16, currency: 'USD' },
      { name: 'Sidecar', price: 16, currency: 'USD' },
      { name: 'Bartender\'s Choice', price: 19, currency: 'USD' },
      { name: 'Golden Hour', price: 17, currency: 'USD' },
      { name: 'Loaded Nachos', price: 14, currency: 'USD' },
      { name: 'Edamame', price: 8, currency: 'USD' },
      { name: 'Chicken Wings', price: 13, currency: 'USD' },
    ],
  },
  {
    name: 'Cobbler',
    address: '서울 종로구 사직로12길 16',
    city: 'Seoul',
    latitude: 37.5753045,
    longitude: 126.9709071,
    description: 'An artful cocktail bar where each drink tells a story.',
    photos: [
      'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=800',
      'https://images.unsplash.com/photo-1560508179-b2c9a3f8e92b?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Espresso Martini', price: 16, currency: 'USD' },
      { name: 'Bee\'s Knees', price: 14, currency: 'USD' },
      { name: 'Margarita', price: 14, currency: 'USD' },
      { name: 'Seoul Sunset', price: 18, currency: 'USD' },
      { name: 'Beef Tartare', price: 22, currency: 'USD' },
      { name: 'Grilled Octopus', price: 19, currency: 'USD' },
      { name: 'Charcuterie Board', price: 22, currency: 'USD' },
    ],
  },
  {
    name: 'Bar Pomme',
    address: '서울 종로구 통인동 135-4',
    city: 'Seoul',
    latitude: 37.5793302,
    longitude: 126.9703248,
    description: 'Expert bartenders serve inventive cocktails in a cozy, dimly-lit atmosphere.',
    photos: [
      'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=800',
      'https://images.unsplash.com/photo-1613412596744-93641adbb8e6?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Espresso Martini', price: 16, currency: 'USD' },
      { name: 'Dark & Stormy', price: 14, currency: 'USD' },
      { name: 'Smoky Horizon', price: 19, currency: 'USD' },
      { name: 'Cherry Blossom Fizz', price: 18, currency: 'USD' },
      { name: 'Olive Tapenade', price: 10, currency: 'USD' },
      { name: 'Cheese Platter', price: 18, currency: 'USD' },
      { name: 'Caprese Salad', price: 13, currency: 'USD' },
    ],
  },
  {
    name: 'Bar Cham',
    address: '서울 종로구 자하문로7길 34',
    city: 'Seoul',
    latitude: 37.5791709,
    longitude: 126.9703851,
    description: 'Creative cocktails meet a relaxed atmosphere in this local favorite.',
    photos: [
      'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800',
      'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=800',
      'https://images.unsplash.com/photo-1570598912132-0ba1dc952b7d?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Tom Collins', price: 13, currency: 'USD' },
      { name: 'Margarita', price: 14, currency: 'USD' },
      { name: 'Velvet Moon', price: 18, currency: 'USD' },
      { name: 'Cherry Blossom Fizz', price: 18, currency: 'USD' },
      { name: 'Truffle Popcorn', price: 10, currency: 'USD' },
      { name: 'Edamame', price: 8, currency: 'USD' },
    ],
  },
  {
    name: 'Drink in Peace',
    address: '서울 종로구 율곡로10길 77',
    city: 'Seoul',
    latitude: 37.5740749,
    longitude: 126.9916042,
    description: 'Creative cocktails meet a relaxed atmosphere in this local favorite.',
    photos: [
      'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800',
      'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Last Word', price: 16, currency: 'USD' },
      { name: 'Caipirinha', price: 13, currency: 'USD' },
      { name: 'Penicillin', price: 16, currency: 'USD' },
      { name: 'Golden Hour', price: 17, currency: 'USD' },
      { name: 'Shrimp Ceviche', price: 17, currency: 'USD' },
      { name: 'Grilled Octopus', price: 19, currency: 'USD' },
    ],
  },
  {
    name: 'Saeseoul',
    address: '서울 종로구 돈화문로11길 28-5 3-5F',
    city: 'Seoul',
    latitude: 37.5728113,
    longitude: 126.9898352,
    description: 'Creative cocktails meet a relaxed atmosphere in this local favorite.',
    photos: [
      'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800',
      'https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=800',
      'https://images.unsplash.com/photo-1602834877751-f850e8f39067?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Clover Club', price: 15, currency: 'USD' },
      { name: 'Boulevardier', price: 16, currency: 'USD' },
      { name: 'House Signature', price: 18, currency: 'USD' },
      { name: 'Prosciutto & Fig', price: 16, currency: 'USD' },
      { name: 'Beef Tartare', price: 22, currency: 'USD' },
      { name: 'Caprese Salad', price: 13, currency: 'USD' },
    ],
  },
  {
    name: 'Waoak',
    address: '서울 종로구 북촌로5나길 3-7',
    city: 'Seoul',
    latitude: 37.5813619,
    longitude: 126.9816498,
    description: 'A neighborhood cocktail gem known for its seasonal menu and warm hospitality.',
    photos: [
      'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=800',
      'https://images.unsplash.com/photo-1560508179-b2c9a3f8e92b?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Cosmopolitan', price: 15, currency: 'USD' },
      { name: 'Pisco Sour', price: 15, currency: 'USD' },
      { name: 'Espresso Martini', price: 16, currency: 'USD' },
      { name: 'House Signature', price: 18, currency: 'USD' },
      { name: 'Cherry Blossom Fizz', price: 18, currency: 'USD' },
      { name: 'Arancini', price: 14, currency: 'USD' },
      { name: 'Edamame', price: 8, currency: 'USD' },
    ],
  },
];
