import type { BarSeedData } from './bar-seed.types.js';

export const barSeedPart02: BarSeedData[] = [
  {
    name: 'Bar Lupin',
    address: '서울 강남구 설릉로160길 5 청담동',
    city: 'Seoul',
    latitude: 37.5263912,
    longitude: 127.0407592,
    description: 'Rare spirits and perfectly executed classics in an elegant setting.',
    photos: [
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
      'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Nikka From The Barrel', price: 20, currency: 'USD' },
      { name: 'Glenfiddich 15yr', price: 30, currency: 'USD' },
      { name: 'Jack Daniel\'s', price: 12, currency: 'USD' },
      { name: 'Clover Club', price: 15, currency: 'USD' },
      { name: 'Chicken Wings', price: 13, currency: 'USD' },
      { name: 'Wagyu Slider', price: 20, currency: 'USD' },
      { name: 'Shrimp Ceviche', price: 17, currency: 'USD' },
    ],
  },
  {
    name: 'The Garrison',
    address: '서울 강남구 신사동 661 지하',
    city: 'Seoul',
    latitude: 37.5274515,
    longitude: 127.0390047,
    description: 'Expert bartenders serve inventive cocktails in a cozy, dimly-lit atmosphere.',
    photos: [
      'https://images.unsplash.com/photo-1621275471769-e6aa344546d5?w=800',
      'https://images.unsplash.com/photo-1588685218599-e7a9a87ac948?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Sazerac', price: 17, currency: 'USD' },
      { name: 'Aperol Spritz', price: 14, currency: 'USD' },
      { name: 'House Signature', price: 18, currency: 'USD' },
      { name: 'Seasonal Special', price: 17, currency: 'USD' },
      { name: 'Smoked Salmon', price: 18, currency: 'USD' },
      { name: 'Edamame', price: 8, currency: 'USD' },
      { name: 'Cheese Platter', price: 18, currency: 'USD' },
    ],
  },
  {
    name: 'Scentique',
    address: '서울 강남구 신사동 643-17',
    city: 'Seoul',
    latitude: 37.5267418,
    longitude: 127.0360766,
    description: 'An artful cocktail bar where each drink tells a story.',
    photos: [
      'https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=800',
      'https://images.unsplash.com/photo-1569924256650-e1c4c3a5e4f0?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Mai Tai', price: 15, currency: 'USD' },
      { name: 'Sidecar', price: 16, currency: 'USD' },
      { name: 'Bartender\'s Choice', price: 19, currency: 'USD' },
      { name: 'Grilled Octopus', price: 19, currency: 'USD' },
      { name: 'Fish & Chips', price: 15, currency: 'USD' },
      { name: 'Loaded Nachos', price: 14, currency: 'USD' },
    ],
  },
  {
    name: 'Bar Chapter One',
    address: '서울 강남구 논현로175길 101 신사동',
    city: 'Seoul',
    latitude: 37.5226481,
    longitude: 127.021152,
    description: 'Step through the secret entrance into a world of craft cocktails and mystery.',
    photos: [
      'https://images.unsplash.com/photo-1575184560884-5f3ece6e636c?w=800',
      'https://images.unsplash.com/photo-1597290282695-edc43d0e7129?w=800',
      'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Boulevardier', price: 16, currency: 'USD' },
      { name: 'Corpse Reviver', price: 16, currency: 'USD' },
      { name: 'Aviation', price: 15, currency: 'USD' },
      { name: 'Seasonal Special', price: 17, currency: 'USD' },
      { name: 'Midnight Garden', price: 20, currency: 'USD' },
      { name: 'Charcuterie Board', price: 22, currency: 'USD' },
      { name: 'Beef Tartare', price: 22, currency: 'USD' },
    ],
  },
  {
    name: 'SAHM',
    address: '서울 강남구 로데오스타빌딩 A동 104호',
    city: 'Seoul',
    latitude: 37.5279733,
    longitude: 127.0372002,
    description: 'An artful cocktail bar where each drink tells a story.',
    photos: [
      'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800',
      'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=800',
      'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Gin & Tonic', price: 12, currency: 'USD' },
      { name: 'Espresso Martini', price: 16, currency: 'USD' },
      { name: 'Smoky Horizon', price: 19, currency: 'USD' },
      { name: 'Wagyu Slider', price: 20, currency: 'USD' },
      { name: 'Edamame', price: 8, currency: 'USD' },
    ],
  },
  {
    name: '브루노뮤직바',
    address: '서울 강남구 논현로 837 원방빌딩 지하1층',
    city: 'Seoul',
    latitude: 37.523291,
    longitude: 127.0279659,
    description: 'A music-forward bar where curated playlists set the mood for great drinks.',
    photos: [
      'https://images.unsplash.com/photo-1588685218599-e7a9a87ac948?w=800',
      'https://images.unsplash.com/photo-1555970348-3a10b197f131?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Hibiki Harmony', price: 26, currency: 'USD' },
      { name: 'Talisker 10yr', price: 22, currency: 'USD' },
      { name: 'Daiquiri', price: 13, currency: 'USD' },
      { name: 'Whiskey Sour', price: 14, currency: 'USD' },
      { name: 'Last Word', price: 16, currency: 'USD' },
      { name: 'Arancini', price: 14, currency: 'USD' },
      { name: 'Olive Tapenade', price: 10, currency: 'USD' },
      { name: 'Anchovy Bruschetta', price: 13, currency: 'USD' },
    ],
  },
  {
    name: 'HILO Seoul',
    address: '서울 강남구 설릉로153길 32 3층',
    city: 'Seoul',
    latitude: 37.5248094,
    longitude: 127.0368303,
    description: 'A sophisticated cocktail bar offering creative, handcrafted drinks in an intimate setting.',
    photos: [
      'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800',
      'https://images.unsplash.com/photo-1556745763-1a6f0ddb0250?w=800',
      'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Caipirinha', price: 13, currency: 'USD' },
      { name: 'Clover Club', price: 15, currency: 'USD' },
      { name: 'Whiskey Sour', price: 14, currency: 'USD' },
      { name: 'Midnight Garden', price: 20, currency: 'USD' },
      { name: 'Grilled Octopus', price: 19, currency: 'USD' },
      { name: 'Anchovy Bruschetta', price: 13, currency: 'USD' },
    ],
  },
  {
    name: 'The Mix Lab',
    address: '서울 강남구 가로수길 19 B1',
    city: 'Seoul',
    latitude: 37.5191811,
    longitude: 127.0229641,
    description: 'A prohibition-era-inspired hideaway serving impeccable cocktails.',
    photos: [
      'https://images.unsplash.com/photo-1560508179-b2c9a3f8e92b?w=800',
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Clover Club', price: 15, currency: 'USD' },
      { name: 'Rob Roy', price: 16, currency: 'USD' },
      { name: 'Golden Hour', price: 17, currency: 'USD' },
      { name: 'Cheese Platter', price: 18, currency: 'USD' },
      { name: 'Chicken Wings', price: 13, currency: 'USD' },
    ],
  },
  {
    name: 'Cinderella Bar',
    address: '서울 성동구 성수동2가 289-247 1층',
    city: 'Seoul',
    latitude: 37.5461793,
    longitude: 127.0548466,
    description: 'A sophisticated cocktail bar offering creative, handcrafted drinks in an intimate setting.',
    photos: [
      'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=800',
      'https://images.unsplash.com/photo-1621275471769-e6aa344546d5?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Gimlet', price: 14, currency: 'USD' },
      { name: 'Daiquiri', price: 13, currency: 'USD' },
      { name: 'Clover Club', price: 15, currency: 'USD' },
      { name: 'House Signature', price: 18, currency: 'USD' },
      { name: 'Bartender\'s Choice', price: 19, currency: 'USD' },
      { name: 'Truffle Fries', price: 12, currency: 'USD' },
      { name: 'Prosciutto & Fig', price: 16, currency: 'USD' },
      { name: 'Loaded Nachos', price: 14, currency: 'USD' },
    ],
  },
];
