import type { BarSeedData } from './bar-seed.types.js';

export const barSeedPart01: BarSeedData[] = [
  {
    name: 'Le Chamber',
    address: '서울 강남구 도산대로55길 42 지하1층',
    city: 'Seoul',
    latitude: 37.5262177,
    longitude: 127.0410396,
    description: 'A hidden speakeasy behind an unassuming entrance. Finding the door is half the fun.',
    photos: [
      'https://images.unsplash.com/photo-1560508179-b2c9a3f8e92b?w=800',
      'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=800',
      'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'French 75', price: 15, currency: 'USD' },
      { name: 'Whiskey Sour', price: 14, currency: 'USD' },
      { name: 'Hanok Breeze', price: 17, currency: 'USD' },
      { name: 'Cheese Platter', price: 18, currency: 'USD' },
      { name: 'Truffle Fries', price: 12, currency: 'USD' },
      { name: 'Charcuterie Board', price: 22, currency: 'USD' },
    ],
  },
  {
    name: 'Zoosindang Gangnam',
    address: '서울 강남구 강남대로96길 9 B1',
    city: 'Seoul',
    latitude: 37.4998801,
    longitude: 127.027735,
    description: 'Expert bartenders serve inventive cocktails in a cozy, dimly-lit atmosphere.',
    photos: [
      'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800',
      'https://images.unsplash.com/photo-1575184560884-5f3ece6e636c?w=800',
      'https://images.unsplash.com/photo-1588685218599-e7a9a87ac948?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Gin & Tonic', price: 12, currency: 'USD' },
      { name: 'Boulevardier', price: 16, currency: 'USD' },
      { name: 'Paloma', price: 13, currency: 'USD' },
      { name: 'House Signature', price: 18, currency: 'USD' },
      { name: 'Bartender\'s Choice', price: 19, currency: 'USD' },
      { name: 'Beef Tartare', price: 22, currency: 'USD' },
      { name: 'Loaded Nachos', price: 14, currency: 'USD' },
      { name: 'Bruschetta', price: 12, currency: 'USD' },
    ],
  },
  {
    name: 'Alice Cheongdam',
    address: '서울 강남구 도산대로55길 47 지하1층',
    city: 'Seoul',
    latitude: 37.5266874,
    longitude: 127.040951,
    description: 'This concealed bar rewards the curious with exceptional drinks and atmosphere.',
    photos: [
      'https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=800',
      'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Tom Collins', price: 13, currency: 'USD' },
      { name: 'Clover Club', price: 15, currency: 'USD' },
      { name: 'Hanok Breeze', price: 17, currency: 'USD' },
      { name: 'Seoul Sunset', price: 18, currency: 'USD' },
      { name: 'Pork Belly Bites', price: 16, currency: 'USD' },
      { name: 'Anchovy Bruschetta', price: 13, currency: 'USD' },
    ],
  },
  {
    name: 'Kiez Seoul',
    address: '서울 강남구 청담동 84-24 B1',
    city: 'Seoul',
    latitude: 37.5265928,
    longitude: 127.0409177,
    description: 'A sophisticated cocktail bar offering creative, handcrafted drinks in an intimate setting.',
    photos: [
      'https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=800',
      'https://images.unsplash.com/photo-1574096079513-d8259312b785?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Paloma', price: 13, currency: 'USD' },
      { name: 'Daiquiri', price: 13, currency: 'USD' },
      { name: 'Bee\'s Knees', price: 14, currency: 'USD' },
      { name: 'House Signature', price: 18, currency: 'USD' },
      { name: 'Smoked Salmon', price: 18, currency: 'USD' },
      { name: 'Charcuterie Board', price: 22, currency: 'USD' },
    ],
  },
  {
    name: 'ZEST SEOUL',
    address: '서울 강남구 도산대로55길 26 하늘빌딩 1층',
    city: 'Seoul',
    latitude: 37.5252611,
    longitude: 127.040778,
    description: 'A sophisticated cocktail bar offering creative, handcrafted drinks in an intimate setting.',
    photos: [
      'https://images.unsplash.com/photo-1560508179-b2c9a3f8e92b?w=800',
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Mojito', price: 13, currency: 'USD' },
      { name: 'Tom Collins', price: 13, currency: 'USD' },
      { name: 'Daiquiri', price: 13, currency: 'USD' },
      { name: 'Rooftop Dream', price: 18, currency: 'USD' },
      { name: 'Neon Alley', price: 19, currency: 'USD' },
      { name: 'Shrimp Ceviche', price: 17, currency: 'USD' },
      { name: 'Chicken Wings', price: 13, currency: 'USD' },
    ],
  },
  {
    name: 'Birdman Bar',
    address: '서울 강남구 가로수길 55-4 지하1층',
    city: 'Seoul',
    latitude: 37.5217055,
    longitude: 127.0224536,
    description: 'Behind an ordinary facade lies an extraordinary cocktail experience.',
    photos: [
      'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=800',
      'https://images.unsplash.com/photo-1621275471769-e6aa344546d5?w=800',
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Cosmopolitan', price: 15, currency: 'USD' },
      { name: 'Rob Roy', price: 16, currency: 'USD' },
      { name: 'Paper Plane', price: 15, currency: 'USD' },
      { name: 'Neon Alley', price: 19, currency: 'USD' },
      { name: 'Cheese Platter', price: 18, currency: 'USD' },
      { name: 'Edamame', price: 8, currency: 'USD' },
      { name: 'Beef Tartare', price: 22, currency: 'USD' },
    ],
  },
  {
    name: 'BAR UGLY',
    address: '서울 강남구 강남대로96길 5 5F',
    city: 'Seoul',
    latitude: 37.4997792,
    longitude: 127.0274413,
    description: 'A neighborhood cocktail gem known for its seasonal menu and warm hospitality.',
    photos: [
      'https://images.unsplash.com/photo-1516600164266-f3b8166ae679?w=800',
      'https://images.unsplash.com/photo-1605270012917-bf157c5a9541?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Paper Plane', price: 15, currency: 'USD' },
      { name: 'Gimlet', price: 14, currency: 'USD' },
      { name: 'Neon Alley', price: 19, currency: 'USD' },
      { name: 'Golden Hour', price: 17, currency: 'USD' },
      { name: 'Loaded Nachos', price: 14, currency: 'USD' },
      { name: 'Bruschetta', price: 12, currency: 'USD' },
    ],
  },
  {
    name: 'Speakeasy Boxing Tiger',
    address: '서울 강남구 신사동 510-3',
    city: 'Seoul',
    latitude: 37.518188,
    longitude: 127.020237,
    description: 'Behind an ordinary facade lies an extraordinary cocktail experience.',
    photos: [
      'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800',
      'https://images.unsplash.com/photo-1602834877751-f850e8f39067?w=800',
      'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Gin & Tonic', price: 12, currency: 'USD' },
      { name: 'Manhattan', price: 16, currency: 'USD' },
      { name: 'Aviation', price: 15, currency: 'USD' },
      { name: 'Seasonal Special', price: 17, currency: 'USD' },
      { name: 'House Signature', price: 18, currency: 'USD' },
      { name: 'Bruschetta', price: 12, currency: 'USD' },
      { name: 'Chicken Wings', price: 13, currency: 'USD' },
    ],
  },
  {
    name: 'MIXOLOGY',
    address: '서울 강남구 도산대로58길 18 지하1층',
    city: 'Seoul',
    latitude: 37.5220856,
    longitude: 127.0412029,
    description: 'A prohibition-era-inspired hideaway serving impeccable cocktails.',
    photos: [
      'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800',
      'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=800',
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Sidecar', price: 16, currency: 'USD' },
      { name: 'Clover Club', price: 15, currency: 'USD' },
      { name: 'Old Fashioned', price: 15, currency: 'USD' },
      { name: 'Neon Alley', price: 19, currency: 'USD' },
      { name: 'Chicken Wings', price: 13, currency: 'USD' },
      { name: 'Beef Tartare', price: 22, currency: 'USD' },
      { name: 'Garlic Shrimp', price: 16, currency: 'USD' },
    ],
  },
];
