import type { BarSeedData } from './bar-seed.types.js';

export const barSeedPart11: BarSeedData[] = [
  {
    name: 'Chaegbar',
    address: '서울 마포구 포은로 90 301호',
    city: 'Seoul',
    latitude: 37.5550858,
    longitude: 126.9052635,
    description: 'Creative cocktails meet a relaxed atmosphere in this local favorite.',
    photos: [
      'https://images.unsplash.com/photo-1597290282695-edc43d0e7129?w=800',
      'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800',
      'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Negroni', price: 14, currency: 'USD' },
      { name: 'Margarita', price: 14, currency: 'USD' },
      { name: 'Seasonal Special', price: 17, currency: 'USD' },
      { name: 'Rooftop Dream', price: 18, currency: 'USD' },
      { name: 'Grilled Octopus', price: 19, currency: 'USD' },
      { name: 'Bruschetta', price: 12, currency: 'USD' },
    ],
  },
  {
    name: 'Tiger Lounge',
    address: '서울 마포구 월드컵로 103-1 2층',
    city: 'Seoul',
    latitude: 37.557766,
    longitude: 126.9082349,
    description: 'Creative cocktails meet a relaxed atmosphere in this local favorite.',
    photos: [
      'https://images.unsplash.com/photo-1588685218599-e7a9a87ac948?w=800',
      'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Corpse Reviver', price: 16, currency: 'USD' },
      { name: 'Dark & Stormy', price: 14, currency: 'USD' },
      { name: 'Golden Hour', price: 17, currency: 'USD' },
      { name: 'Loaded Nachos', price: 14, currency: 'USD' },
      { name: 'Cheese Platter', price: 18, currency: 'USD' },
      { name: 'Mozzarella Sticks', price: 11, currency: 'USD' },
    ],
  },
  {
    name: 'Bar 81',
    address: '서울 송파구 올림픽로 300 롯데월드타워',
    city: 'Seoul',
    latitude: 37.5127207,
    longitude: 127.1025581,
    description: 'Expert bartenders serve inventive cocktails in a cozy, dimly-lit atmosphere.',
    photos: [
      'https://images.unsplash.com/photo-1540189065-3c6af6b0ea18?w=800',
      'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Whiskey Sour', price: 14, currency: 'USD' },
      { name: 'Last Word', price: 16, currency: 'USD' },
      { name: 'Tom Collins', price: 13, currency: 'USD' },
      { name: 'House Signature', price: 18, currency: 'USD' },
      { name: 'Velvet Moon', price: 18, currency: 'USD' },
      { name: 'Caprese Salad', price: 13, currency: 'USD' },
      { name: 'Garlic Shrimp', price: 16, currency: 'USD' },
      { name: 'Anchovy Bruschetta', price: 13, currency: 'USD' },
    ],
  },
  {
    name: 'Latitude32',
    address: '서울 송파구 잠실로 209',
    city: 'Seoul',
    latitude: 37.5135953,
    longitude: 127.1063093,
    description: 'Expert bartenders serve inventive cocktails in a cozy, dimly-lit atmosphere.',
    photos: [
      'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800',
      'https://images.unsplash.com/photo-1556745763-1a6f0ddb0250?w=800',
      'https://images.unsplash.com/photo-1578664182354-aedb42c42281?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Manhattan', price: 16, currency: 'USD' },
      { name: 'Caipirinha', price: 13, currency: 'USD' },
      { name: 'Seasonal Special', price: 17, currency: 'USD' },
      { name: 'Baked Brie', price: 15, currency: 'USD' },
      { name: 'Caprese Salad', price: 13, currency: 'USD' },
    ],
  },
  {
    name: 'Conan',
    address: '서울 송파구 백제고분로7길 42-16',
    city: 'Seoul',
    latitude: 37.5100538,
    longitude: 127.0837387,
    description: 'A neighborhood cocktail gem known for its seasonal menu and warm hospitality.',
    photos: [
      'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=800',
      'https://images.unsplash.com/photo-1560508179-b2c9a3f8e92b?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Manhattan', price: 16, currency: 'USD' },
      { name: 'Sidecar', price: 16, currency: 'USD' },
      { name: 'Bartender\'s Choice', price: 19, currency: 'USD' },
      { name: 'Seasonal Special', price: 17, currency: 'USD' },
      { name: 'Bruschetta', price: 12, currency: 'USD' },
      { name: 'Truffle Fries', price: 12, currency: 'USD' },
    ],
  },
  {
    name: 'Leseuteu (Bar Rest)',
    address: '서울 용산구 이태원동 580',
    city: 'Seoul',
    latitude: 37.5374536,
    longitude: 126.9872659,
    description: 'Discover carefully selected wines paired with artisanal small plates.',
    photos: [
      'https://images.unsplash.com/photo-1605270012917-bf157c5a9541?w=800',
      'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800',
      'https://images.unsplash.com/photo-1485872299829-c673f5194813?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'House Red Wine', price: 12, currency: 'USD' },
      { name: 'Natural Wine Glass', price: 16, currency: 'USD' },
      { name: 'Prosecco', price: 13, currency: 'USD' },
      { name: 'Chardonnay', price: 15, currency: 'USD' },
      { name: 'Pork Belly Bites', price: 16, currency: 'USD' },
      { name: 'Charcuterie Board', price: 22, currency: 'USD' },
      { name: 'Gimlet', price: 14, currency: 'USD' },
    ],
  },
  {
    name: 'Big Lights',
    address: '서울 용산구 한남대로20길 61-17',
    city: 'Seoul',
    latitude: 37.5354427,
    longitude: 127.0101606,
    description: 'An intimate wine bar with a rotating selection of global and Korean wines.',
    photos: [
      'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800',
      'https://images.unsplash.com/photo-1540189065-3c6af6b0ea18?w=800',
      'https://images.unsplash.com/photo-1595951821958-0f5fcdfcb7e1?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Sangiovese', price: 15, currency: 'USD' },
      { name: 'House Red Wine', price: 12, currency: 'USD' },
      { name: 'Chardonnay', price: 15, currency: 'USD' },
      { name: 'Anchovy Bruschetta', price: 13, currency: 'USD' },
      { name: 'Chicken Wings', price: 13, currency: 'USD' },
      { name: 'Truffle Fries', price: 12, currency: 'USD' },
      { name: 'Negroni', price: 14, currency: 'USD' },
    ],
  },
  {
    name: '37 Surero',
    address: '37 Sure-ro, Wabu-eup, Namyangju-si, Gyeonggi-do',
    city: 'Namyangju',
    latitude: 37.587701,
    longitude: 127.21622,
    description: 'Creative cocktails meet a relaxed atmosphere in this local favorite.',
    photos: [
      'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800',
      'https://images.unsplash.com/photo-1569924256650-e1c4c3a5e4f0?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Espresso Martini', price: 16, currency: 'USD' },
      { name: 'Corpse Reviver', price: 16, currency: 'USD' },
      { name: 'Aperol Spritz', price: 14, currency: 'USD' },
      { name: 'Seasonal Special', price: 17, currency: 'USD' },
      { name: 'Loaded Nachos', price: 14, currency: 'USD' },
      { name: 'Shrimp Ceviche', price: 17, currency: 'USD' },
    ],
  },
];
