import type { BarSeedData } from './bar-seed.types.js';

export const barSeedPart10: BarSeedData[] = [
  {
    name: '연남고집',
    address: '서울 마포구 연남동 228-55 지층',
    city: 'Seoul',
    latitude: 37.5618793,
    longitude: 126.9247341,
    description: 'Traditional Korean rice wine meets modern ambiance in this makgeolli-focused bar.',
    photos: [
      'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800',
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'House Makgeolli', price: 10, currency: 'USD' },
      { name: 'Premium Makgeolli', price: 14, currency: 'USD' },
      { name: 'Sparkling Makgeolli', price: 12, currency: 'USD' },
      { name: 'Onion Rings', price: 10, currency: 'USD' },
      { name: 'Truffle Fries', price: 12, currency: 'USD' },
      { name: 'Anchovy Bruschetta', price: 13, currency: 'USD' },
      { name: 'Smoked Salmon', price: 18, currency: 'USD' },
    ],
  },
  {
    name: '연남어리',
    address: '서울 마포구 연남동 229-56 지하1층',
    city: 'Seoul',
    latitude: 37.562785,
    longitude: 126.9246523,
    description: 'An artful cocktail bar where each drink tells a story.',
    photos: [
      'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800',
      'https://images.unsplash.com/photo-1540189065-3c6af6b0ea18?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Paloma', price: 13, currency: 'USD' },
      { name: 'Margarita', price: 14, currency: 'USD' },
      { name: 'Paper Plane', price: 15, currency: 'USD' },
      { name: 'Rooftop Dream', price: 18, currency: 'USD' },
      { name: 'Seoul Sunset', price: 18, currency: 'USD' },
      { name: 'Smoked Salmon', price: 18, currency: 'USD' },
      { name: 'Caprese Salad', price: 13, currency: 'USD' },
      { name: 'Prosciutto & Fig', price: 16, currency: 'USD' },
    ],
  },
  {
    name: 'Yeonju Vin Affair',
    address: '서울 마포구 동교로46길 13 반지층',
    city: 'Seoul',
    latitude: 37.5623561,
    longitude: 126.9256119,
    description: 'A curated wine bar offering natural and organic wines in a relaxed setting.',
    photos: [
      'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=800',
      'https://images.unsplash.com/photo-1609951651556-5334e2706168?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Sauvignon Blanc', price: 14, currency: 'USD' },
      { name: 'Champagne Glass', price: 25, currency: 'USD' },
      { name: 'House Red Wine', price: 12, currency: 'USD' },
      { name: 'Prosecco', price: 13, currency: 'USD' },
      { name: 'Truffle Fries', price: 12, currency: 'USD' },
      { name: 'Baked Brie', price: 15, currency: 'USD' },
      { name: 'Onion Rings', price: 10, currency: 'USD' },
      { name: 'Mai Tai', price: 15, currency: 'USD' },
    ],
  },
  {
    name: '계월 바',
    address: '서울 마포구 월드컵로19길 18',
    city: 'Seoul',
    latitude: 37.5566275,
    longitude: 126.9081479,
    description: 'A sophisticated cocktail bar offering creative, handcrafted drinks in an intimate setting.',
    photos: [
      'https://images.unsplash.com/photo-1569924256650-e1c4c3a5e4f0?w=800',
      'https://images.unsplash.com/photo-1574096079513-d8259312b785?w=800',
      'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Gin & Tonic', price: 12, currency: 'USD' },
      { name: 'Paper Plane', price: 15, currency: 'USD' },
      { name: 'Daiquiri', price: 13, currency: 'USD' },
      { name: 'Neon Alley', price: 19, currency: 'USD' },
      { name: 'Rooftop Dream', price: 18, currency: 'USD' },
      { name: 'Chicken Wings', price: 13, currency: 'USD' },
      { name: 'Garlic Shrimp', price: 16, currency: 'USD' },
    ],
  },
  {
    name: '단바 서울 danbar',
    address: '서울 마포구 망원로2길 87',
    city: 'Seoul',
    latitude: 37.553577,
    longitude: 126.9038027,
    description: 'A sophisticated cocktail bar offering creative, handcrafted drinks in an intimate setting.',
    photos: [
      'https://images.unsplash.com/photo-1540189065-3c6af6b0ea18?w=800',
      'https://images.unsplash.com/photo-1525268323446-0505b6fe7778?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'French 75', price: 15, currency: 'USD' },
      { name: 'Manhattan', price: 16, currency: 'USD' },
      { name: 'Espresso Martini', price: 16, currency: 'USD' },
      { name: 'Smoky Horizon', price: 19, currency: 'USD' },
      { name: 'Velvet Moon', price: 18, currency: 'USD' },
      { name: 'Caprese Salad', price: 13, currency: 'USD' },
      { name: 'Bruschetta', price: 12, currency: 'USD' },
    ],
  },
  {
    name: '초쿤바 Chokoon bar',
    address: '서울 마포구 망원동 404-7',
    city: 'Seoul',
    latitude: 37.5547423,
    longitude: 126.9039302,
    description: 'A neighborhood cocktail gem known for its seasonal menu and warm hospitality.',
    photos: [
      'https://images.unsplash.com/photo-1595951821958-0f5fcdfcb7e1?w=800',
      'https://images.unsplash.com/photo-1560508179-b2c9a3f8e92b?w=800',
      'https://images.unsplash.com/photo-1621275471769-e6aa344546d5?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Rob Roy', price: 16, currency: 'USD' },
      { name: 'Pisco Sour', price: 15, currency: 'USD' },
      { name: 'Gimlet', price: 14, currency: 'USD' },
      { name: 'Rooftop Dream', price: 18, currency: 'USD' },
      { name: 'Smoky Horizon', price: 19, currency: 'USD' },
      { name: 'Anchovy Bruschetta', price: 13, currency: 'USD' },
      { name: 'Charcuterie Board', price: 22, currency: 'USD' },
    ],
  },
  {
    name: 'LeDevine',
    address: '서울 마포구 희우정로16길 25 3층',
    city: 'Seoul',
    latitude: 37.5546596,
    longitude: 126.9033895,
    description: 'Discover carefully selected wines paired with artisanal small plates.',
    photos: [
      'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800',
      'https://images.unsplash.com/photo-1587223962930-cb7f31384c19?w=800',
      'https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'House Red Wine', price: 12, currency: 'USD' },
      { name: 'Champagne Glass', price: 25, currency: 'USD' },
      { name: 'Chardonnay', price: 15, currency: 'USD' },
      { name: 'House White Wine', price: 12, currency: 'USD' },
      { name: 'Arancini', price: 14, currency: 'USD' },
      { name: 'Onion Rings', price: 10, currency: 'USD' },
      { name: 'Pork Belly Bites', price: 16, currency: 'USD' },
      { name: 'Last Word', price: 16, currency: 'USD' },
    ],
  },
  {
    name: 'Sipo',
    address: '서울 마포구 월드컵로19길 18',
    city: 'Seoul',
    latitude: 37.5566528,
    longitude: 126.9081048,
    description: 'Natural wines and seasonal bites in a warm, welcoming atmosphere.',
    photos: [
      'https://images.unsplash.com/photo-1587223962930-cb7f31384c19?w=800',
      'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Pinot Noir', price: 16, currency: 'USD' },
      { name: 'House Red Wine', price: 12, currency: 'USD' },
      { name: 'Sangiovese', price: 15, currency: 'USD' },
      { name: 'Shrimp Ceviche', price: 17, currency: 'USD' },
      { name: 'Edamame', price: 8, currency: 'USD' },
      { name: 'Chicken Wings', price: 13, currency: 'USD' },
      { name: 'Espresso Martini', price: 16, currency: 'USD' },
    ],
  },
];
