import type { BarSeedData } from './bar-seed.types.js';

export const barSeedPart09: BarSeedData[] = [
  {
    name: 'SIDE NOTE CLUB',
    address: '서울 마포구 양화로 130',
    city: 'Seoul',
    latitude: 37.5544318,
    longitude: 126.921251,
    description: 'Creative cocktails meet a relaxed atmosphere in this local favorite.',
    photos: [
      'https://images.unsplash.com/photo-1570598912132-0ba1dc952b7d?w=800',
      'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Sidecar', price: 16, currency: 'USD' },
      { name: 'Manhattan', price: 16, currency: 'USD' },
      { name: 'Penicillin', price: 16, currency: 'USD' },
      { name: 'Hanok Breeze', price: 17, currency: 'USD' },
      { name: 'Charcuterie Board', price: 22, currency: 'USD' },
      { name: 'Loaded Nachos', price: 14, currency: 'USD' },
    ],
  },
  {
    name: 'Diss',
    address: '서울 마포구 363-23',
    city: 'Seoul',
    latitude: 37.5511192,
    longitude: 126.9224786,
    description: 'A neighborhood cocktail gem known for its seasonal menu and warm hospitality.',
    photos: [
      'https://images.unsplash.com/photo-1560508179-b2c9a3f8e92b?w=800',
      'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=800',
      'https://images.unsplash.com/photo-1574096079513-d8259312b785?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Pisco Sour', price: 15, currency: 'USD' },
      { name: 'Paloma', price: 13, currency: 'USD' },
      { name: 'Last Word', price: 16, currency: 'USD' },
      { name: 'Bartender\'s Choice', price: 19, currency: 'USD' },
      { name: 'Golden Hour', price: 17, currency: 'USD' },
      { name: 'Arancini', price: 14, currency: 'USD' },
      { name: 'Beef Tartare', price: 22, currency: 'USD' },
      { name: 'Grilled Octopus', price: 19, currency: 'USD' },
    ],
  },
  {
    name: 'Howl in the Bar',
    address: '서울 마포구 동교로38길 33-15 연남동',
    city: 'Seoul',
    latitude: 37.5618128,
    longitude: 126.9261064,
    description: 'Creative cocktails meet a relaxed atmosphere in this local favorite.',
    photos: [
      'https://images.unsplash.com/photo-1605270012917-bf157c5a9541?w=800',
      'https://images.unsplash.com/photo-1575184560884-5f3ece6e636c?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Paloma', price: 13, currency: 'USD' },
      { name: 'Penicillin', price: 16, currency: 'USD' },
      { name: 'Velvet Moon', price: 18, currency: 'USD' },
      { name: 'Beef Tartare', price: 22, currency: 'USD' },
      { name: 'Pork Belly Bites', price: 16, currency: 'USD' },
    ],
  },
  {
    name: '블렌딩바 연남',
    address: '서울 마포구 동교로38길 33-9',
    city: 'Seoul',
    latitude: 37.5616472,
    longitude: 126.9259966,
    description: 'Creative cocktails meet a relaxed atmosphere in this local favorite.',
    photos: [
      'https://images.unsplash.com/photo-1613412596744-93641adbb8e6?w=800',
      'https://images.unsplash.com/photo-1569924256650-e1c4c3a5e4f0?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Manhattan', price: 16, currency: 'USD' },
      { name: 'Aviation', price: 15, currency: 'USD' },
      { name: 'Seasonal Special', price: 17, currency: 'USD' },
      { name: 'Golden Hour', price: 17, currency: 'USD' },
      { name: 'Wagyu Slider', price: 20, currency: 'USD' },
      { name: 'Anchovy Bruschetta', price: 13, currency: 'USD' },
    ],
  },
  {
    name: 'oyoyoy 연남',
    address: '서울 마포구 연남동 260-24',
    city: 'Seoul',
    latitude: 37.5612824,
    longitude: 126.9247173,
    description: 'Discover carefully selected wines paired with artisanal small plates.',
    photos: [
      'https://images.unsplash.com/photo-1613412596744-93641adbb8e6?w=800',
      'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Champagne Glass', price: 25, currency: 'USD' },
      { name: 'Rosé by the Glass', price: 14, currency: 'USD' },
      { name: 'Sangiovese', price: 15, currency: 'USD' },
      { name: 'Prosecco', price: 13, currency: 'USD' },
      { name: 'Beef Tartare', price: 22, currency: 'USD' },
      { name: 'Onion Rings', price: 10, currency: 'USD' },
      { name: 'Clover Club', price: 15, currency: 'USD' },
    ],
  },
  {
    name: 'BAR Catalyst',
    address: '서울 마포구 42 24 3F',
    city: 'Seoul',
    latitude: 37.5616877,
    longitude: 126.9265368,
    description: 'Creative cocktails meet a relaxed atmosphere in this local favorite.',
    photos: [
      'https://images.unsplash.com/photo-1569924256650-e1c4c3a5e4f0?w=800',
      'https://images.unsplash.com/photo-1588685218599-e7a9a87ac948?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Sazerac', price: 17, currency: 'USD' },
      { name: 'Espresso Martini', price: 16, currency: 'USD' },
      { name: 'Neon Alley', price: 19, currency: 'USD' },
      { name: 'Edamame', price: 8, currency: 'USD' },
      { name: 'Pork Belly Bites', price: 16, currency: 'USD' },
      { name: 'Charcuterie Board', price: 22, currency: 'USD' },
    ],
  },
  {
    name: '미드나잇 라운지',
    address: '서울 마포구 연남동 228-2 2층 202호',
    city: 'Seoul',
    latitude: 37.5628325,
    longitude: 126.9260451,
    description: 'A sophisticated cocktail bar offering creative, handcrafted drinks in an intimate setting.',
    photos: [
      'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800',
      'https://images.unsplash.com/photo-1540189065-3c6af6b0ea18?w=800',
      'https://images.unsplash.com/photo-1621275471769-e6aa344546d5?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Corpse Reviver', price: 16, currency: 'USD' },
      { name: 'Old Fashioned', price: 15, currency: 'USD' },
      { name: 'Negroni', price: 14, currency: 'USD' },
      { name: 'House Signature', price: 18, currency: 'USD' },
      { name: 'Seoul Sunset', price: 18, currency: 'USD' },
      { name: 'Arancini', price: 14, currency: 'USD' },
      { name: 'Olive Tapenade', price: 10, currency: 'USD' },
      { name: 'Bruschetta', price: 12, currency: 'USD' },
    ],
  },
  {
    name: 'SALON de MIN',
    address: '서울 마포구 연남동 228-42 2층',
    city: 'Seoul',
    latitude: 37.5623964,
    longitude: 126.9246151,
    description: 'An artful cocktail bar where each drink tells a story.',
    photos: [
      'https://images.unsplash.com/photo-1485872299829-c673f5194813?w=800',
      'https://images.unsplash.com/photo-1621275471769-e6aa344546d5?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Espresso Martini', price: 16, currency: 'USD' },
      { name: 'Sazerac', price: 17, currency: 'USD' },
      { name: 'Hanok Breeze', price: 17, currency: 'USD' },
      { name: 'Neon Alley', price: 19, currency: 'USD' },
      { name: 'Truffle Popcorn', price: 10, currency: 'USD' },
      { name: 'Baked Brie', price: 15, currency: 'USD' },
    ],
  },
];
