import type { BarSeedData } from './bar-seed.types.js';

export const barSeedPart08: BarSeedData[] = [
  {
    name: '올디스 하우스',
    address: '서울 중구 수표로 58',
    city: 'Seoul',
    latitude: 37.5664213,
    longitude: 126.9898578,
    description: 'Natural wines and seasonal bites in a warm, welcoming atmosphere.',
    photos: [
      'https://images.unsplash.com/photo-1575184560884-5f3ece6e636c?w=800',
      'https://images.unsplash.com/photo-1602834877751-f850e8f39067?w=800',
      'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Riesling', price: 14, currency: 'USD' },
      { name: 'Natural Wine Glass', price: 16, currency: 'USD' },
      { name: 'Champagne Glass', price: 25, currency: 'USD' },
      { name: 'Charcuterie Board', price: 22, currency: 'USD' },
      { name: 'Cheese Platter', price: 18, currency: 'USD' },
      { name: 'Mojito', price: 13, currency: 'USD' },
    ],
  },
  {
    name: 'BAR CIAO',
    address: '서울 중구 수표로 48-7 101호',
    city: 'Seoul',
    latitude: 37.5656226,
    longitude: 126.9903657,
    description: 'Natural wines and seasonal bites in a warm, welcoming atmosphere.',
    photos: [
      'https://images.unsplash.com/photo-1574096079513-d8259312b785?w=800',
      'https://images.unsplash.com/photo-1540189065-3c6af6b0ea18?w=800',
      'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Sauvignon Blanc', price: 14, currency: 'USD' },
      { name: 'Champagne Glass', price: 25, currency: 'USD' },
      { name: 'Prosecco', price: 13, currency: 'USD' },
      { name: 'Riesling', price: 14, currency: 'USD' },
      { name: 'Anchovy Bruschetta', price: 13, currency: 'USD' },
      { name: 'Charcuterie Board', price: 22, currency: 'USD' },
      { name: 'Shrimp Ceviche', price: 17, currency: 'USD' },
      { name: 'Negroni', price: 14, currency: 'USD' },
    ],
  },
  {
    name: 'Philosophy Lounge',
    address: '서울 중구 충무로 21-19 1층',
    city: 'Seoul',
    latitude: 37.5632153,
    longitude: 126.9919149,
    description: 'A distinguished bar with a deep whiskey library and knowledgeable bartenders.',
    photos: [
      'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800',
      'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800',
      'https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Jameson', price: 12, currency: 'USD' },
      { name: 'Monkey Shoulder', price: 16, currency: 'USD' },
      { name: 'Mai Tai', price: 15, currency: 'USD' },
      { name: 'Baked Brie', price: 15, currency: 'USD' },
      { name: 'Cheese Platter', price: 18, currency: 'USD' },
      { name: 'Fish & Chips', price: 15, currency: 'USD' },
    ],
  },
  {
    name: 'Hongdae PUB SEVEN PUB',
    address: '서울 마포구 동교동 198-13',
    city: 'Seoul',
    latitude: 37.5588853,
    longitude: 126.9231602,
    description: 'A welcoming pub with craft drinks, hearty food, and a lively atmosphere.',
    photos: [
      'https://images.unsplash.com/photo-1485872299829-c673f5194813?w=800',
      'https://images.unsplash.com/photo-1602834877751-f850e8f39067?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Stout Draft', price: 9, currency: 'USD' },
      { name: 'Craft Beer Flight', price: 15, currency: 'USD' },
      { name: 'Pale Ale', price: 8, currency: 'USD' },
      { name: 'Sour Beer', price: 10, currency: 'USD' },
      { name: 'Beef Tartare', price: 22, currency: 'USD' },
      { name: 'Onion Rings', price: 10, currency: 'USD' },
      { name: 'Garlic Shrimp', price: 16, currency: 'USD' },
      { name: 'Clover Club', price: 15, currency: 'USD' },
    ],
  },
  {
    name: 'd.still',
    address: '서울 마포구 와우산로15길 10',
    city: 'Seoul',
    latitude: 37.5499568,
    longitude: 126.9224828,
    description: 'A distinguished bar with a deep whiskey library and knowledgeable bartenders.',
    photos: [
      'https://images.unsplash.com/photo-1569924256650-e1c4c3a5e4f0?w=800',
      'https://images.unsplash.com/photo-1574096079513-d8259312b785?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Nikka From The Barrel', price: 20, currency: 'USD' },
      { name: 'Yamazaki 12yr', price: 32, currency: 'USD' },
      { name: 'Talisker 10yr', price: 22, currency: 'USD' },
      { name: 'Aperol Spritz', price: 14, currency: 'USD' },
      { name: 'Beef Tartare', price: 22, currency: 'USD' },
      { name: 'Garlic Shrimp', price: 16, currency: 'USD' },
      { name: 'Prosciutto & Fig', price: 16, currency: 'USD' },
    ],
  },
  {
    name: '세븐틴벌스데이',
    address: '서울 마포구 동막로7길 56',
    city: 'Seoul',
    latitude: 37.5501207,
    longitude: 126.920202,
    description: 'A sophisticated cocktail bar offering creative, handcrafted drinks in an intimate setting.',
    photos: [
      'https://images.unsplash.com/photo-1588685218599-e7a9a87ac948?w=800',
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
      'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Daiquiri', price: 13, currency: 'USD' },
      { name: 'Aviation', price: 15, currency: 'USD' },
      { name: 'Hanok Breeze', price: 17, currency: 'USD' },
      { name: 'Golden Hour', price: 17, currency: 'USD' },
      { name: 'Cheese Platter', price: 18, currency: 'USD' },
      { name: 'Caprese Salad', price: 13, currency: 'USD' },
      { name: 'Loaded Nachos', price: 14, currency: 'USD' },
    ],
  },
  {
    name: 'Little Big',
    address: '서울 마포구 와우산로35길 71-3',
    city: 'Seoul',
    latitude: 37.556353,
    longitude: 126.926926,
    description: 'Expert bartenders serve inventive cocktails in a cozy, dimly-lit atmosphere.',
    photos: [
      'https://images.unsplash.com/photo-1540189065-3c6af6b0ea18?w=800',
      'https://images.unsplash.com/photo-1569924256650-e1c4c3a5e4f0?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Old Fashioned', price: 15, currency: 'USD' },
      { name: 'Paper Plane', price: 15, currency: 'USD' },
      { name: 'Rooftop Dream', price: 18, currency: 'USD' },
      { name: 'Smoked Salmon', price: 18, currency: 'USD' },
      { name: 'Grilled Octopus', price: 19, currency: 'USD' },
    ],
  },
  {
    name: 'White Rabbit',
    address: '서울 마포구 와우산로33길 4 B1-F3',
    city: 'Seoul',
    latitude: 37.5551587,
    longitude: 126.9301618,
    description: 'Natural wines and seasonal bites in a warm, welcoming atmosphere.',
    photos: [
      'https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=800',
      'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Pinot Noir', price: 16, currency: 'USD' },
      { name: 'House White Wine', price: 12, currency: 'USD' },
      { name: 'Natural Wine Glass', price: 16, currency: 'USD' },
      { name: 'Mozzarella Sticks', price: 11, currency: 'USD' },
      { name: 'Smoked Salmon', price: 18, currency: 'USD' },
      { name: 'Wagyu Slider', price: 20, currency: 'USD' },
      { name: 'Bee\'s Knees', price: 14, currency: 'USD' },
    ],
  },
];
