import type { BarSeedData } from './bar-seed.types.js';

export const barSeedPart12: BarSeedData[] = [
  {
    name: 'Red Dog',
    address: '473-2 Deokso-ri, Wabu-eup, Namyangju-si, Gyeonggi-do',
    city: 'Namyangju',
    latitude: 37.586366,
    longitude: 127.212023,
    description: 'Behind an ordinary facade lies an extraordinary cocktail experience.',
    photos: [
      'https://images.unsplash.com/photo-1605270012917-bf157c5a9541?w=800',
      'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=800',
      'https://images.unsplash.com/photo-1541532713592-79a0317b6b77?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Boulevardier', price: 16, currency: 'USD' },
      { name: 'Aviation', price: 15, currency: 'USD' },
      { name: 'Sazerac', price: 17, currency: 'USD' },
      { name: 'Seasonal Special', price: 17, currency: 'USD' },
      { name: 'Rooftop Dream', price: 18, currency: 'USD' },
      { name: 'Olive Tapenade', price: 10, currency: 'USD' },
      { name: 'Anchovy Bruschetta', price: 13, currency: 'USD' },
    ],
  },
  {
    name: 'Zeus Bar',
    address: '112 Maetdol-ro, Hwado-eup, Namyangju-si, Gyeonggi-do',
    city: 'Namyangju',
    latitude: 37.65749672,
    longitude: 127.30250359,
    description: 'Creative cocktails meet a relaxed atmosphere in this local favorite.',
    photos: [
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
      'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'French 75', price: 15, currency: 'USD' },
      { name: 'Whiskey Sour', price: 14, currency: 'USD' },
      { name: 'Aperol Spritz', price: 14, currency: 'USD' },
      { name: 'Smoky Horizon', price: 19, currency: 'USD' },
      { name: 'Neon Alley', price: 19, currency: 'USD' },
      { name: 'Arancini', price: 14, currency: 'USD' },
      { name: 'Bruschetta', price: 12, currency: 'USD' },
      { name: 'Onion Rings', price: 10, currency: 'USD' },
    ],
  },
  {
    name: 'Wolmun Sanghoe',
    address: '976-1 Dogok-ri, Wabu-eup, Namyangju-si, Gyeonggi-do',
    city: 'Namyangju',
    latitude: 37.58075575,
    longitude: 127.21803577,
    description: 'A curated wine bar offering natural and organic wines in a relaxed setting.',
    photos: [
      'https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=800',
      'https://images.unsplash.com/photo-1602834877751-f850e8f39067?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Sauvignon Blanc', price: 14, currency: 'USD' },
      { name: 'Rosé by the Glass', price: 14, currency: 'USD' },
      { name: 'Natural Wine Glass', price: 16, currency: 'USD' },
      { name: 'Baked Brie', price: 15, currency: 'USD' },
      { name: 'Grilled Octopus', price: 19, currency: 'USD' },
      { name: 'Sidecar', price: 16, currency: 'USD' },
    ],
  },
  {
    name: 'All That Jazz',
    address: '216 Itaewon-ro, Yongsan-gu, Seoul, 2F',
    city: 'Seoul',
    latitude: 37.53467877,
    longitude: 126.99812944,
    description: 'Live jazz performances complement expertly crafted cocktails in this soulful venue.',
    photos: [
      'https://images.unsplash.com/photo-1609951651556-5334e2706168?w=800',
      'https://images.unsplash.com/photo-1602834877751-f850e8f39067?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Ardbeg 10yr', price: 24, currency: 'USD' },
      { name: 'Tom Collins', price: 13, currency: 'USD' },
      { name: 'Whiskey Sour', price: 14, currency: 'USD' },
      { name: 'Paloma', price: 13, currency: 'USD' },
      { name: 'Bruschetta', price: 12, currency: 'USD' },
      { name: 'Onion Rings', price: 10, currency: 'USD' },
    ],
  },
  {
    name: 'The Booth Seongsu',
    address: '136 Wangsimni-ro, Seongdong-gu, Seoul',
    city: 'Seoul',
    latitude: 37.5496852,
    longitude: 127.0445577,
    description: 'A vibrant craft beer destination with rotating taps and hearty pub fare.',
    photos: [
      'https://images.unsplash.com/photo-1609951651556-5334e2706168?w=800',
      'https://images.unsplash.com/photo-1587223962930-cb7f31384c19?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Pilsner', price: 8, currency: 'USD' },
      { name: 'Porter', price: 9, currency: 'USD' },
      { name: 'Stout Draft', price: 9, currency: 'USD' },
      { name: 'Grilled Octopus', price: 19, currency: 'USD' },
      { name: 'Shrimp Ceviche', price: 17, currency: 'USD' },
      { name: 'Onion Rings', price: 10, currency: 'USD' },
      { name: 'Paper Plane', price: 15, currency: 'USD' },
    ],
  },
  {
    name: 'Sunset Record',
    address: '11 Eulji-ro 12-gil, Jung-gu, Seoul, 2F',
    city: 'Seoul',
    latitude: 37.56564676,
    longitude: 126.99125233,
    description: 'Vinyl records spin as you sip cocktails in this retro-inspired hidden bar.',
    photos: [
      'https://images.unsplash.com/photo-1560508179-b2c9a3f8e92b?w=800',
      'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800',
      'https://images.unsplash.com/photo-1485872299829-c673f5194813?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Jack Daniel\'s', price: 12, currency: 'USD' },
      { name: 'Ardbeg 10yr', price: 24, currency: 'USD' },
      { name: 'Tom Collins', price: 13, currency: 'USD' },
      { name: 'Old Fashioned', price: 15, currency: 'USD' },
      { name: 'Mojito', price: 13, currency: 'USD' },
      { name: 'Baked Brie', price: 15, currency: 'USD' },
      { name: 'Onion Rings', price: 10, currency: 'USD' },
    ],
  },
  {
    name: 'Floating',
    address: '137 Toegye-ro, Jung-gu, Seoul, L7 Hotel Myeongdong Rooftop',
    city: 'Seoul',
    latitude: 37.5614009,
    longitude: 126.98696727,
    description: 'A sophisticated cocktail bar offering creative, handcrafted drinks in an intimate setting.',
    photos: [
      'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800',
      'https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Penicillin', price: 16, currency: 'USD' },
      { name: 'Dark & Stormy', price: 14, currency: 'USD' },
      { name: 'Smoky Horizon', price: 19, currency: 'USD' },
      { name: 'Bartender\'s Choice', price: 19, currency: 'USD' },
      { name: 'Smoked Salmon', price: 18, currency: 'USD' },
      { name: 'Pork Belly Bites', price: 16, currency: 'USD' },
      { name: 'Beef Tartare', price: 22, currency: 'USD' },
    ],
  },
  {
    name: 'Vin Vin Vin',
    address: '서울 용산구 녹사평대로46길 13 1층',
    city: 'Seoul',
    latitude: 37.5372781,
    longitude: 126.9876204,
    description: 'A curated wine bar offering natural and organic wines in a relaxed setting.',
    photos: [
      'https://images.unsplash.com/photo-1621275471769-e6aa344546d5?w=800',
      'https://images.unsplash.com/photo-1556745763-1a6f0ddb0250?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Champagne Glass', price: 25, currency: 'USD' },
      { name: 'Pinot Noir', price: 16, currency: 'USD' },
      { name: 'Prosecco', price: 13, currency: 'USD' },
      { name: 'Shrimp Ceviche', price: 17, currency: 'USD' },
      { name: 'Anchovy Bruschetta', price: 13, currency: 'USD' },
      { name: 'Olive Tapenade', price: 10, currency: 'USD' },
      { name: 'Cosmopolitan', price: 15, currency: 'USD' },
    ],
  },
];
