import type { BarSeedData } from './bar-seed.types.js';

export const barSeedPart07: BarSeedData[] = [
  {
    name: 'Hidden Look Seoul Music',
    address: '서울 중구 을지로35길 26-1',
    city: 'Seoul',
    latitude: 37.5678849,
    longitude: 127.0013645,
    description: 'A music-forward bar where curated playlists set the mood for great drinks.',
    photos: [
      'https://images.unsplash.com/photo-1587223962930-cb7f31384c19?w=800',
      'https://images.unsplash.com/photo-1570598912132-0ba1dc952b7d?w=800',
      'https://images.unsplash.com/photo-1541532713592-79a0317b6b77?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Balvenie 14yr', price: 30, currency: 'USD' },
      { name: 'Nikka From The Barrel', price: 20, currency: 'USD' },
      { name: 'Tom Collins', price: 13, currency: 'USD' },
      { name: 'Bee\'s Knees', price: 14, currency: 'USD' },
      { name: 'Boulevardier', price: 16, currency: 'USD' },
      { name: 'Smoked Salmon', price: 18, currency: 'USD' },
      { name: 'Loaded Nachos', price: 14, currency: 'USD' },
      { name: 'Edamame', price: 8, currency: 'USD' },
    ],
  },
  {
    name: 'oyoyoy 을지로',
    address: '서울 중구 수표로 48-7 1층',
    city: 'Seoul',
    latitude: 37.5656404,
    longitude: 126.9903866,
    description: 'Discover carefully selected wines paired with artisanal small plates.',
    photos: [
      'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=800',
      'https://images.unsplash.com/photo-1588685218599-e7a9a87ac948?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Orange Wine', price: 18, currency: 'USD' },
      { name: 'Sauvignon Blanc', price: 14, currency: 'USD' },
      { name: 'Pinot Noir', price: 16, currency: 'USD' },
      { name: 'Pork Belly Bites', price: 16, currency: 'USD' },
      { name: 'Baked Brie', price: 15, currency: 'USD' },
      { name: 'Wagyu Slider', price: 20, currency: 'USD' },
      { name: 'Sazerac', price: 17, currency: 'USD' },
    ],
  },
  {
    name: 'The Ranch Brewing Euljiro',
    address: '서울 중구 을지로12길 11',
    city: 'Seoul',
    latitude: 37.5656331,
    longitude: 126.9911556,
    description: 'A vibrant craft beer destination with rotating taps and hearty pub fare.',
    photos: [
      'https://images.unsplash.com/photo-1574096079513-d8259312b785?w=800',
      'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Pale Ale', price: 8, currency: 'USD' },
      { name: 'Porter', price: 9, currency: 'USD' },
      { name: 'IPA Draft', price: 9, currency: 'USD' },
      { name: 'Pilsner', price: 8, currency: 'USD' },
      { name: 'Loaded Nachos', price: 14, currency: 'USD' },
      { name: 'Cheese Platter', price: 18, currency: 'USD' },
      { name: 'Negroni', price: 14, currency: 'USD' },
    ],
  },
  {
    name: 'Euljiro Mantic',
    address: '서울 중구 을지로3가 295-1',
    city: 'Seoul',
    latitude: 37.5661827,
    longitude: 126.9922881,
    description: 'A distinguished bar with a deep whiskey library and knowledgeable bartenders.',
    photos: [
      'https://images.unsplash.com/photo-1555970348-3a10b197f131?w=800',
      'https://images.unsplash.com/photo-1569924256650-e1c4c3a5e4f0?w=800',
      'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Monkey Shoulder', price: 16, currency: 'USD' },
      { name: 'Ardbeg 10yr', price: 24, currency: 'USD' },
      { name: 'Gimlet', price: 14, currency: 'USD' },
      { name: 'Boulevardier', price: 16, currency: 'USD' },
      { name: 'Fish & Chips', price: 15, currency: 'USD' },
      { name: 'Cheese Platter', price: 18, currency: 'USD' },
      { name: 'Loaded Nachos', price: 14, currency: 'USD' },
    ],
  },
  {
    name: 'MicroVinylHouse',
    address: '서울 중구 을지로27길 27 2층',
    city: 'Seoul',
    latitude: 37.5680111,
    longitude: 126.999002,
    description: 'Vinyl records spin as you sip cocktails in this retro-inspired hidden bar.',
    photos: [
      'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800',
      'https://images.unsplash.com/photo-1569924256650-e1c4c3a5e4f0?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Monkey Shoulder', price: 16, currency: 'USD' },
      { name: 'Manhattan', price: 16, currency: 'USD' },
      { name: 'Caipirinha', price: 13, currency: 'USD' },
      { name: 'Charcuterie Board', price: 22, currency: 'USD' },
      { name: 'Edamame', price: 8, currency: 'USD' },
      { name: 'Garlic Shrimp', price: 16, currency: 'USD' },
    ],
  },
  {
    name: '평균율',
    address: '서울 중구 충무로4길 3',
    city: 'Seoul',
    latitude: 37.5650458,
    longitude: 126.9929868,
    description: 'Natural wines and seasonal bites in a warm, welcoming atmosphere.',
    photos: [
      'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800',
      'https://images.unsplash.com/photo-1541532713592-79a0317b6b77?w=800',
      'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Pinot Noir', price: 16, currency: 'USD' },
      { name: 'Champagne Glass', price: 25, currency: 'USD' },
      { name: 'Sangiovese', price: 15, currency: 'USD' },
      { name: 'Prosecco', price: 13, currency: 'USD' },
      { name: 'Baked Brie', price: 15, currency: 'USD' },
      { name: 'Shrimp Ceviche', price: 17, currency: 'USD' },
      { name: 'Cheese Platter', price: 18, currency: 'USD' },
      { name: 'Sazerac', price: 17, currency: 'USD' },
    ],
  },
  {
    name: 'Euljiro Brewing',
    address: '서울 중구 수표로 48-16',
    city: 'Seoul',
    latitude: 37.5654623,
    longitude: 126.9907264,
    description: 'A vibrant craft beer destination with rotating taps and hearty pub fare.',
    photos: [
      'https://images.unsplash.com/photo-1516600164266-f3b8166ae679?w=800',
      'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Pale Ale', price: 8, currency: 'USD' },
      { name: 'Stout Draft', price: 9, currency: 'USD' },
      { name: 'Sour Beer', price: 10, currency: 'USD' },
      { name: 'Fish & Chips', price: 15, currency: 'USD' },
      { name: 'Truffle Fries', price: 12, currency: 'USD' },
      { name: 'Dark & Stormy', price: 14, currency: 'USD' },
    ],
  },
  {
    name: 'Ace 4 Club',
    address: '서울 중구 을지로 105',
    city: 'Seoul',
    latitude: 37.5663941,
    longitude: 126.9895395,
    description: 'An artful cocktail bar where each drink tells a story.',
    photos: [
      'https://images.unsplash.com/photo-1574096079513-d8259312b785?w=800',
      'https://images.unsplash.com/photo-1525268323446-0505b6fe7778?w=800',
    ],
    operatingHours: [
      { dayOfWeek: 'MON', openTime: '00:00', closeTime: '00:00', isClosed: true },
      { dayOfWeek: 'TUE', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'WED', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'THU', openTime: '19:00', closeTime: '02:00', isClosed: false },
      { dayOfWeek: 'FRI', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SAT', openTime: '19:00', closeTime: '03:00', isClosed: false },
      { dayOfWeek: 'SUN', openTime: '18:00', closeTime: '00:00', isClosed: false },
    ],
    menuItems: [
      { name: 'Margarita', price: 14, currency: 'USD' },
      { name: 'Bee\'s Knees', price: 14, currency: 'USD' },
      { name: 'Rooftop Dream', price: 18, currency: 'USD' },
      { name: 'Golden Hour', price: 17, currency: 'USD' },
      { name: 'Onion Rings', price: 10, currency: 'USD' },
      { name: 'Edamame', price: 8, currency: 'USD' },
    ],
  },
];
